name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  backend-tests:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./backend

    steps:
      - name: Checkout du code
        uses: actions/checkout@v4

      - name: Configurer Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Installer les dépendances
        run: pip install -r requirements.txt

      - name: Lancer les tests
        run: pytest tests/ -v

  frontend-build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./frontend

    steps:
      - name: Checkout du code
        uses: actions/checkout@v4

      - name: Configurer Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Installer les dépendances
        run: npm install

      - name: Build de production
        run: npm run build

  docker-build:
    runs-on: ubuntu-latest
    needs: [backend-tests, frontend-build]

    steps:
      - name: Checkout du code
        uses: actions/checkout@v4

      - name: Build de l'image backend
        run: docker build -t diabete-backend ./backend

      - name: Build de l'image frontend
        run: docker build -t diabete-frontend ./frontend